export const MENU = [
  {
    id: "menu-1",
    title: "개발",
    url: "/dev",
  },
  {
    id: "menu-2",
    title: "나머지",
    url: "/others",
  },
  {
    id: "menu-3",
    title: "작품",
    url: "/product",
  },
  {
    id: "menu-4",
    title: "소개",
    url: "/about-me",
  },
];

export const PROJECTS = [
  {
    id: "project-1",
    title: "Upshare",
    description: "취약한 파일공유 서비스",
    size: "1인 개발",
    duration: "2024.04 ~ 2024.07",
    logoUrl: "/logos/upshare.svg",
    imageUrl: "/images/upshare.png",
    bg: "bg-slate-100",
    from: "from-slate-200",
    to: "to-slate-400",
  },
  {
    id: "project-2",
    title: "한국수력원자력 ERP 고도화 프로젝트",
    description: "경영관리분야 ERP 전환 개발, BSC 성과지표 고도화",
    size: "130명+",
    duration: "2023.01 ~ 2024.02",
    logoUrl: "/logos/khnp.svg",
    imageUrl: "/images/khnp.png",
    bg: "bg-neutral-100",
    from: "bg-[#dde5b6]",
    to: "",
  },
  {
    id: "project-3",
    title: "React YearMonth Picker",
    description: "리액트 날짜선택 UI 라이브러리",
    size: "1인 개발",
    duration: "2024.08 ~ 2024.08",
    logoUrl: "/logos/calendar.png",
    imageUrl: "/images/ym-picker.png",
    bg: "bg-rose-100",
    from: "from-rose-200",
    to: "to-rose-400",
  },
  {
    id: "project-4",
    title: "이인거(Twicycle)",
    description: "이인승 자전거 위치 찾기",
    size: "1인 개발",
    duration: "2024.08 ~ 2024.08",
    logoUrl: "/logos/twicycle.svg",
    imageUrl: "/images/twicycle.png",
    bg: "bg-slate-100",
    from: "from-slate-300",
    to: "to-slate-500",
  },
];
